#!/bin/bash
# Times execution of file and outputs results (ignores invalid options).
# Usage: ./telemetry -[f|c|s] [arg] ...
# Options:
#   -f: Path to executable file to test.
#   -c: Number of count to run program (defaults to 100).
#   -s: Precision of the result (defaults to 5).

while getopts ":f:c:s" opt; do
    case $opt in
        f)
            file=$OPTARG
            ;;
        c)
            count=$OPTARG
            ;;
        s)
            scale=$OPTARG
            ;;
    esac
done

if [ -z $file ] || ! [ -x $file ]; then
    file=./out
fi

if [ -z $count ]; then
    count=1000
fi

if [ -z $scale ]; then
    scale=6
fi

result=`{ time for i in $(seq $count); do $file 1>/dev/null; done; } 2>&1 |\
            grep real |\
            grep -Po "\d+m\d\.\d+"`
minutes=`echo "$result" |\
            grep -Po "^\d+"`
seconds=`echo "$result" |\
            grep -Po "m.+" |\
            sed 's/m//' |\
            xargs echo "$minutes*60+" |\
            bc |\
            xargs echo "scale=$scale; $count^-1*" |\
            bc`

echo "Total time taken: ${result}s"
echo "Average time per execution: ${seconds}s"
